/**
 * @file navigation.ts
 * @description Helper utilities for semantic link navigation and event handling.
 * Ensures consistent handling of primary left clicks for SPA routing while
 * preserving native browser behaviors for middle clicks, context menus, and modifier keys.
 */

/**
 * Handles click events on documentation anchor elements.
 * Preserves native browser behaviors for non-primary clicks (middle-click, right-click)
 * and key combinations (Ctrl, Cmd, Shift, Alt).
 *
 * @param e MouseEvent generated by user interaction
 * @param targetHash Target fragment identifier URL (e.g., "#docs#goroutine")
 * @param onSameTabCallback Optional custom navigation logic for in-app SPA transitions
 */
export function handleDocLinkClick(
  e: MouseEvent,
  targetHash: string,
  onSameTabCallback?: () => void,
): void {
  // Allow native browser opening mechanics when middle-click or key modifiers are active
  if (e.button !== 0 || e.ctrlKey || e.metaKey || e.shiftKey || e.altKey) {
    return;
  }

  // Intercept standard primary left-click for smooth SPA hash transition
  e.preventDefault();

  if (onSameTabCallback) {
    onSameTabCallback();
  } else {
    window.location.hash = targetHash;
  }
}
